# Generated by Django 3.2.9 on 2021-11-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211113_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
