# Generated by Django 3.2.9 on 2021-11-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
